version: "3.8"
services:
  db:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5401:5432
    volumes:
      - ./pgdata/development:/var/lib/postgresql/data/pgdata
  testdb:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5402:5432
