// This file is autogenerated by Redwood and will be overwitten periodically

import { db } from 'src/lib/db'
import datamodel from 'src/models/datamodel'
import { RedwoodRecord } from '@redwoodjs/record'

RedwoodRecord.db = db
RedwoodRecord.schema = datamodel

import Album from 'src/models/Album'
import Band from 'src/models/Band'
import BandMember from 'src/models/BandMember'
import Musician from 'src/models/Musician'
import Song from 'src/models/Song'

Album.requiredModels = [Band, Song]
Band.requiredModels = [Album, BandMember]
BandMember.requiredModels = [Band, Musician]
Musician.requiredModels = [BandMember, Song]
Song.requiredModels = [Album, Musician]

export { Album, Band, BandMember, Musician, Song }
